### ISSUE TITLE
Escape Sequences not Fully Implemented

### ISSUE THREAD

**Issue by dhurlburtusa** [rubensworks/rdf-string-ttl.js#1]
That is, special characters in the values of the various RDF/JS Terms are not escaped when serialized to a string.

For example, `RdfString.termToString(RdfDataModel.literal('a\nb\rc'))` should return the following character sequence `"a\nb\rc"` (nine characters) which as a JavaScript string could be written as `"\"a\\nb\\rc\""` when using double quotes as the delimiters.

I believe the library is only handling escaping of quotes.

- See https://www.w3.org/TR/n-triples/ and search for "escap" to find info about escaping.
- See https://www.w3.org/TR/turtle/#sec-escapes and search for "escap" to find info about escaping.

Note: There are different ways the serialized form of a literal may be written depending on whether the term is used in a line-based serialized format (e.g., N-Triples or N-Quads) or a block-based serialized format (e.g., Turtle or TriG). That is, the line-ending characters don't have to be escaped if the surrounding literal delimiters are `'''` or `"""` triple quotes (which is allowed in Turtle or TriG). If the literal delimiters are `'` or `"`, then line-ending characters must be escaped.

Because we don't ultimately know where the output of `RdfString.termToString` is going to be used, using a block-based form of the term would only work in a Turtle or TriG document. So, I would recommend outputting N-Triples or N-Quads compatible character sequences (which would make the name of this library with the `-ttl` ending sort of a misnomer.)

Note: The N3 library is handling the escaping of literals. You can see the start of the escape sequencing code at https://github.com/rdfjs/N3.js/blob/master/src/N3Writer.js#L11.

I think it would be great if the escape sequencing code was added to this library and N3 was updated to use this library to handle the serialization of RDF terms.

**Comment by rubensworks** [comment]
Thanks for the comment @dhurlburtusa!

Better escaping support is definitely needed indeed.

> Because we don't ultimately know where the output of RdfString.termToString is going to be used, using a block-based form of the term would only work in a Turtle or TriG document.

We could add an option to `termToString` to allow the user to decide between these quoting modes.

> I think it would be great if the escape sequencing code was added to this library

👍 
I do not have an immediate need myself for this (possibly in the future), so this is not on my roadmap at the moment.
Happy to accept a PR for this though.
