### ISSUE TITLE
Incorrect escaping of IRIs

### ISSUE THREAD

**Issue by benjay10** [rubensworks/rdf-string-ttl.js#5]
Hi, me again

With https://github.com/rubensworks/rdf-string-ttl.js/pull/3, when the IRI contains some special but allowed characters, they are converted to their unicode escape sequence, while they should be left alone. This slipped through the cracks, because such scenario was not included in the tests, and was working before the merge. :facepalm: 

E.g. a `namedNode('http://this-is-an-example.com')` should be converted to `<http://this-is-an-example.com>`, but instead is converted to `<http://this\\u002dis\\u002dan\\u002dexample.com>`.

This is because the RegEx, the second part that is supposed to only match on surrogate pairs, also matches on the `-` (and potentially even more). I don't understand, because that `-` is clearly not in the ranges for that surrogate pair.

[This on RegExr](https://regexr.com/71vtv) demonstrates the surrogate pair part and how it matches the `-`.

**Comment by rubensworks** [comment]
Oops, that's not good.

**Comment by benjay10** [comment]
Sorry this is happening, it feels like this is partially my fault for not making sure the test included more specific cases like this. :disappointed: 

I actually just noticed because I did a fresh `npm install` and noticed you published a new version literally minutes ago.

**Comment by rubensworks** [comment]
That's ok. Can you PR a fix?
